name: ci-blenderbim-daily

on:
  push:
    paths:
      - '.github/workflows/ci-blenderbim-daily.yml'
  schedule:
    #          ┌───────────── minute (0 - 59)
    #          │  ┌───────────── hour (0 - 23)
    #          │  │ ┌───────────── day of the month (1 - 31)
    #          │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #          │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #          *  * * * *
      - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update-extensions-repo:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout BBIMDailyBuilds repository
          uses: actions/checkout@v2
          with:
            repository: Andrej730/BBIMDailyBuilds
            token: ${{ secrets.GITHUB_TOKEN }}
            path: BBIMDailyBuilds

        - name: Replace index.json with an empty file
          run: echo -n > BBIMDailyBuilds/index.json

        - name: Commit and push changes
          run: |
            set -x # echo shell commands
            wget -q -O blender.tar.xz https://ftp.nluug.nl/pub/graphics/blender/release/Blender4.2/blender-4.2.0-linux-x64.tar.xz
            tar -xf blender.tar.xz
            BLENDER_PATH=$(find blender*/ -maxdepth 0 -exec readlink -f {} \;)
            export PATH="$PATH:$BLENDER_PATH"
            blender --version
            cd BBIMDailyBuilds
            pip install -r requirements.txt
            python setup_extensions_repo.py --last-tag
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add index.json
            git add readme.md
            git commit -m "Update"
            git push

        - name: Run blenderbim tests
          run: |
            set -x -e # echo shell commands
            BLENDER_PATH=$(find blender*/ -maxdepth 0 -exec readlink -f {} \;)
            export PATH="$PATH:$BLENDER_PATH"
            blenderbim_zip="$(pwd)/$(ls BBIMDailyBuilds/blenderbim_py311*-linux-x64.zip)"
            blender --version
            blender --command extension install-file -r user_default -e $blenderbim_zip
            blender --command extension list

            wget -q -O sverchok.zip https://github.com/nortikin/sverchok/archive/refs/heads/master.zip
            # ifcsverchok expecting sverchok to be named "sverchok" and not "sverchok-master".
            unzip -q sverchok.zip
            mv sverchok-master sverchok
            zip -q -r sverchok.zip sverchok
            rm -r sverchok
            blender --command extension install-file -r user_default sverchok.zip

            git clone https://github.com/IfcOpenShell/IfcOpenShell.git IfcOpenShell
            cd IfcOpenShell/src/ifcsverchok
            make dist
            sverchok_zip="$(pwd)/dist/$(ls dist)"
            blender --command extension install-file -r user_default $sverchok_zip

            cd ../blenderbim
            pip install pytest-blender
            blender --background --python scripts/setup_pytest.py
            blender --python-expr "import blenderbim; print(blenderbim.bbim_semver); import ifcopenshell; print(ifcopenshell.version)" --background
            make test
